services:
  db:
    image: postgres:17
    container_name: db_instagram
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    image: instagram_service:latest
    build: .
    container_name: web_instagram_service
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: bash -c "poetry run python manage.py makemigrations && poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8300"
    ports:
      - "8300:8300"


volumes:
  postgres_data:
