# Generated by Django 6.0.2 on 2026-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='instagram_media_id',
            field=models.BigIntegerField(unique=True, verbose_name='Post`s ID'),
        ),
    ]
