# Generated by Django 6.0.2 on 2026-02-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_instagram_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='instagram_comment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
